name:                 runtime
version:              0.1.0.0
visibility:           public
id:                   runtime-0.1.0.0-inplace
key:                  runtime-0.1.0.0-inplace
license:              BSD-3-Clause
copyright:            2021 Author name here
maintainer:           example@example.com
author:               Author name here
homepage:             https://github.com/githubuser/runtime#readme
description:
    Please see the README on GitHub at <https://github.com/githubuser/runtime#readme>

abi:                  inplace
exposed:              True
exposed-modules:      Imp ImpIO ImpParser ImpProgram ImpSBV ImpVCGen
hidden-modules:       Paths_runtime
import-dirs:
    /home/luis-pinochet/Documentos/runTimeCalculator/runtime/dist-newstyle/build/x86_64-linux/ghc-9.10.3/runtime-0.1.0.0/build

library-dirs:
    /home/luis-pinochet/Documentos/runTimeCalculator/runtime/dist-newstyle/build/x86_64-linux/ghc-9.10.3/runtime-0.1.0.0/build

library-dirs-static:
    /home/luis-pinochet/Documentos/runTimeCalculator/runtime/dist-newstyle/build/x86_64-linux/ghc-9.10.3/runtime-0.1.0.0/build

dynamic-library-dirs:
    /home/luis-pinochet/Documentos/runTimeCalculator/runtime/dist-newstyle/build/x86_64-linux/ghc-9.10.3/runtime-0.1.0.0/build

data-dir:             /home/luis-pinochet/Documentos/runTimeCalculator/runtime/.
hs-libraries:         HSruntime-0.1.0.0-inplace
depends:
    base-4.20.2.0-f074 containers-0.7-d31f parsec-3.1.18.0-69b3
    sbv-14.7-c4beb94fbfd3a8773f69e4cd80723fc39de1e7c0facafa1199792c386e68766b
    semigroups-0.20.1-94899a024aaf3fcaa8c5cfea09dbb0d526aa99014e4e84e2744f9bfe8b7d9bc1
    text-2.1.3-df3f transformers-0.6.1.1-5a1c

haddock-interfaces:
    /home/luis-pinochet/Documentos/runTimeCalculator/runtime/dist-newstyle/build/x86_64-linux/ghc-9.10.3/runtime-0.1.0.0/doc/html/runtime/runtime.haddock

haddock-html:
    /home/luis-pinochet/Documentos/runTimeCalculator/runtime/dist-newstyle/build/x86_64-linux/ghc-9.10.3/runtime-0.1.0.0/doc/html/runtime
